"""
Synthetic AML transaction datasets for all tasks.
Each task returns:
  - transactions: list of transaction dicts
  - ground_truth: list of {transaction_id, true_label, risk_level, explanation}
  - investigation_budget: int
"""

from typing import Any

# ── Task 1: triage_basic (Easy) ──────────────────────────────────────────────

TRIAGE_BASIC_TRANSACTIONS = [
    {
        "id": "TXN001",
        "amount": 9500.00,
        "sender_country": "US",
        "receiver_country": "US",
        "transaction_type": "cash",
        "velocity_24h": 3,
        "is_round_number": False,
        "prior_flags": 0,
        "amount_vs_avg_ratio": 1.1,
        "high_risk_country": False,
        "structuring_indicator": True,
        "shell_company_indicator": False,
        "pep_involved": False,
        "notes": "Cash deposit just under $10k reporting threshold. Third such deposit this week.",
    },
    {
        "id": "TXN002",
        "amount": 250000.00,
        "sender_country": "KP",  # North Korea
        "receiver_country": "US",
        "transaction_type": "wire",
        "velocity_24h": 1,
        "is_round_number": True,
        "prior_flags": 5,
        "amount_vs_avg_ratio": 42.0,
        "high_risk_country": True,
        "structuring_indicator": False,
        "shell_company_indicator": True,
        "pep_involved": True,
        "notes": "Wire from North Korean entity to a US LLC. Sender is OFAC-listed.",
    },
    {
        "id": "TXN003",
        "amount": 3200.00,
        "sender_country": "US",
        "receiver_country": "US",
        "transaction_type": "internal",
        "velocity_24h": 2,
        "is_round_number": False,
        "prior_flags": 0,
        "amount_vs_avg_ratio": 0.95,
        "high_risk_country": False,
        "structuring_indicator": False,
        "shell_company_indicator": False,
        "pep_involved": False,
        "notes": "Regular bi-weekly payroll transfer for small business. Consistent with historical pattern.",
    },
    {
        "id": "TXN004",
        "amount": 15000.00,
        "sender_country": "DE",
        "receiver_country": "US",
        "transaction_type": "wire",
        "velocity_24h": 1,
        "is_round_number": False,
        "prior_flags": 0,
        "amount_vs_avg_ratio": 1.3,
        "high_risk_country": False,
        "structuring_indicator": False,
        "shell_company_indicator": False,
        "pep_involved": False,
        "notes": "Invoice payment from German supplier. Invoice on file, goods confirmed delivered.",
    },
    {
        "id": "TXN005",
        "amount": 500000.00,
        "sender_country": "IR",  # Iran
        "receiver_country": "AE",
        "transaction_type": "crypto",
        "velocity_24h": 12,
        "is_round_number": True,
        "prior_flags": 8,
        "amount_vs_avg_ratio": 87.0,
        "high_risk_country": True,
        "structuring_indicator": False,
        "shell_company_indicator": True,
        "pep_involved": False,
        "notes": "Large crypto transfer from sanctioned Iranian IP. Passes through known mixer address.",
    },
]

TRIAGE_BASIC_GROUND_TRUTH = [
    {"transaction_id": "TXN001", "true_label": "suspicious", "risk_level": "medium",
     "explanation": "Classic structuring (smurfing) — intentional deposits just under $10k CTR threshold."},
    {"transaction_id": "TXN002", "true_label": "suspicious", "risk_level": "high",
     "explanation": "OFAC-listed North Korean entity, PEP, shell company, massive amount spike."},
    {"transaction_id": "TXN003", "true_label": "legitimate", "risk_level": "low",
     "explanation": "Consistent payroll pattern, no red flags."},
    {"transaction_id": "TXN004", "true_label": "legitimate", "risk_level": "low",
     "explanation": "Documented trade payment with invoice, low-risk jurisdiction."},
    {"transaction_id": "TXN005", "true_label": "suspicious", "risk_level": "high",
     "explanation": "Sanctions evasion via crypto mixer from Iran to UAE shell."},
]

TRIAGE_BASIC_BUDGET = 2


# ── Task 2: triage_network (Medium) ──────────────────────────────────────────

TRIAGE_NETWORK_TRANSACTIONS = [
    {
        "id": "NET001",
        "amount": 8900.00,
        "sender_country": "MX",
        "receiver_country": "US",
        "transaction_type": "wire",
        "velocity_24h": 5,
        "is_round_number": False,
        "prior_flags": 1,
        "amount_vs_avg_ratio": 2.1,
        "high_risk_country": False,
        "structuring_indicator": True,
        "shell_company_indicator": False,
        "pep_involved": False,
        "notes": "Wire from Mexico. Sender 'MX_CORP_A' has sent 5 similar sub-$10k wires today.",
    },
    {
        "id": "NET002",
        "amount": 8750.00,
        "sender_country": "MX",
        "receiver_country": "US",
        "transaction_type": "wire",
        "velocity_24h": 5,
        "is_round_number": False,
        "prior_flags": 1,
        "amount_vs_avg_ratio": 2.0,
        "high_risk_country": False,
        "structuring_indicator": True,
        "shell_company_indicator": False,
        "pep_involved": False,
        "notes": "Same sender 'MX_CORP_A' as NET001. Different receiver account.",
    },
    {
        "id": "NET003",
        "amount": 45000.00,
        "sender_country": "US",
        "receiver_country": "LU",
        "transaction_type": "wire",
        "velocity_24h": 1,
        "is_round_number": False,
        "prior_flags": 0,
        "amount_vs_avg_ratio": 8.5,
        "high_risk_country": False,
        "structuring_indicator": False,
        "shell_company_indicator": True,
        "pep_involved": False,
        "notes": "US receiver of NET001/NET002 funds now sending to Luxembourg shell. Layering.",
    },
    {
        "id": "NET004",
        "amount": 2200.00,
        "sender_country": "US",
        "receiver_country": "US",
        "transaction_type": "internal",
        "velocity_24h": 1,
        "is_round_number": False,
        "prior_flags": 0,
        "amount_vs_avg_ratio": 1.05,
        "high_risk_country": False,
        "structuring_indicator": False,
        "shell_company_indicator": False,
        "pep_involved": False,
        "notes": "Rent payment from personal account. Landlord confirmed. Consistent monthly.",
    },
    {
        "id": "NET005",
        "amount": 175000.00,
        "sender_country": "LU",
        "receiver_country": "AE",
        "transaction_type": "wire",
        "velocity_24h": 1,
        "is_round_number": False,
        "prior_flags": 0,
        "amount_vs_avg_ratio": 0.0,  # new entity, no history
        "high_risk_country": False,
        "structuring_indicator": False,
        "shell_company_indicator": True,
        "pep_involved": True,
        "notes": "Luxembourg shell (receiver of NET003) now sends to UAE. PEP in UAE is beneficial owner.",
    },
    {
        "id": "NET006",
        "amount": 6800.00,
        "sender_country": "US",
        "receiver_country": "US",
        "transaction_type": "cash",
        "velocity_24h": 2,
        "is_round_number": False,
        "prior_flags": 0,
        "amount_vs_avg_ratio": 1.2,
        "high_risk_country": False,
        "structuring_indicator": False,
        "shell_company_indicator": False,
        "pep_involved": False,
        "notes": "ATM withdrawal. Consistent with customer's spending pattern. No flags.",
    },
    {
        "id": "NET007",
        "amount": 9200.00,
        "sender_country": "MX",
        "receiver_country": "US",
        "transaction_type": "wire",
        "velocity_24h": 5,
        "is_round_number": False,
        "prior_flags": 1,
        "amount_vs_avg_ratio": 2.15,
        "high_risk_country": False,
        "structuring_indicator": True,
        "shell_company_indicator": False,
        "pep_involved": False,
        "notes": "Third wire from 'MX_CORP_A' today. Pattern strongly indicates structuring network.",
    },
    {
        "id": "NET008",
        "amount": 50000.00,
        "sender_country": "US",
        "receiver_country": "US",
        "transaction_type": "wire",
        "velocity_24h": 1,
        "is_round_number": True,
        "prior_flags": 0,
        "amount_vs_avg_ratio": 1.8,
        "high_risk_country": False,
        "structuring_indicator": False,
        "shell_company_indicator": False,
        "pep_involved": False,
        "notes": "Real estate earnest money deposit. Purchase agreement on file. Attorney escrow account.",
    },
    {
        "id": "NET009",
        "amount": 12000.00,
        "sender_country": "NG",
        "receiver_country": "US",
        "transaction_type": "wire",
        "velocity_24h": 1,
        "is_round_number": False,
        "prior_flags": 2,
        "amount_vs_avg_ratio": 3.2,
        "high_risk_country": True,
        "structuring_indicator": False,
        "shell_company_indicator": False,
        "pep_involved": True,
        "notes": "Wire from Nigerian PEP (state governor's family member) to US personal account.",
    },
    {
        "id": "NET010",
        "amount": 890.00,
        "sender_country": "US",
        "receiver_country": "US",
        "transaction_type": "internal",
        "velocity_24h": 1,
        "is_round_number": False,
        "prior_flags": 0,
        "amount_vs_avg_ratio": 0.98,
        "high_risk_country": False,
        "structuring_indicator": False,
        "shell_company_indicator": False,
        "pep_involved": False,
        "notes": "Utility bill autopayment. Recurring monthly. Completely normal.",
    },
]

TRIAGE_NETWORK_GROUND_TRUTH = [
    {"transaction_id": "NET001", "true_label": "suspicious", "risk_level": "high",
     "explanation": "Part of structuring network from MX_CORP_A — coordinated sub-$10k wires."},
    {"transaction_id": "NET002", "true_label": "suspicious", "risk_level": "high",
     "explanation": "Same structuring network as NET001 — same sender, same day."},
    {"transaction_id": "NET003", "true_label": "suspicious", "risk_level": "high",
     "explanation": "Layering — receives structured funds then moves to Luxembourg shell."},
    {"transaction_id": "NET004", "true_label": "legitimate", "risk_level": "low",
     "explanation": "Normal rent payment with documentation."},
    {"transaction_id": "NET005", "true_label": "suspicious", "risk_level": "high",
     "explanation": "Integration stage — PEP in UAE receives layered funds from Luxembourg shell."},
    {"transaction_id": "NET006", "true_label": "legitimate", "risk_level": "low",
     "explanation": "Normal ATM usage consistent with profile."},
    {"transaction_id": "NET007", "true_label": "suspicious", "risk_level": "high",
     "explanation": "Third wire in the MX structuring network on the same day."},
    {"transaction_id": "NET008", "true_label": "legitimate", "risk_level": "low",
     "explanation": "Documented real estate transaction with attorney escrow."},
    {"transaction_id": "NET009", "true_label": "suspicious", "risk_level": "medium",
     "explanation": "PEP from high-risk jurisdiction sending to personal US account without explanation."},
    {"transaction_id": "NET010", "true_label": "legitimate", "risk_level": "low",
     "explanation": "Routine utility autopayment."},
]

TRIAGE_NETWORK_BUDGET = 3


# ── Task 3: triage_adversarial (Hard) ────────────────────────────────────────

TRIAGE_ADVERSARIAL_TRANSACTIONS = [
    {
        "id": "ADV001",
        "amount": 4950.00,
        "sender_country": "US",
        "receiver_country": "US",
        "transaction_type": "cash",
        "velocity_24h": 1,
        "is_round_number": False,
        "prior_flags": 0,
        "amount_vs_avg_ratio": 1.1,
        "high_risk_country": False,
        "structuring_indicator": False,  # individual txn looks clean
        "shell_company_indicator": False,
        "pep_involved": False,
        "notes": "Small cash deposit. Customer claims savings from freelance work. Alone looks fine.",
    },
    {
        "id": "ADV002",
        "amount": 4800.00,
        "sender_country": "US",
        "receiver_country": "US",
        "transaction_type": "cash",
        "velocity_24h": 1,
        "is_round_number": False,
        "prior_flags": 0,
        "amount_vs_avg_ratio": 1.05,
        "high_risk_country": False,
        "structuring_indicator": False,
        "shell_company_indicator": False,
        "pep_involved": False,
        "notes": "Same account as ADV001, deposited 3 days later. Still under threshold individually.",
    },
    {
        "id": "ADV003",
        "amount": 85000.00,
        "sender_country": "CN",
        "receiver_country": "US",
        "transaction_type": "wire",
        "velocity_24h": 1,
        "is_round_number": False,
        "prior_flags": 0,
        "amount_vs_avg_ratio": 1.4,
        "high_risk_country": False,
        "structuring_indicator": False,
        "shell_company_indicator": False,
        "pep_involved": False,
        "notes": "Trade payment for 'consulting services'. Invoice value matches but service is vague. Over-invoicing suspected.",
    },
    {
        "id": "ADV004",
        "amount": 22000.00,
        "sender_country": "US",
        "receiver_country": "CH",
        "transaction_type": "wire",
        "velocity_24h": 1,
        "is_round_number": False,
        "prior_flags": 0,
        "amount_vs_avg_ratio": 2.1,
        "high_risk_country": False,
        "structuring_indicator": False,
        "shell_company_indicator": False,
        "pep_involved": False,
        "notes": "Payment to Swiss 'investment manager'. No publicly registered firm found. Possibly mirror trade setup.",
    },
    {
        "id": "ADV005",
        "amount": 22000.00,
        "sender_country": "CH",
        "receiver_country": "RU",
        "transaction_type": "wire",
        "velocity_24h": 1,
        "is_round_number": False,
        "prior_flags": 0,
        "amount_vs_avg_ratio": 0.0,
        "high_risk_country": True,
        "structuring_indicator": False,
        "shell_company_indicator": True,
        "pep_involved": False,
        "notes": "Swiss entity (receiver of ADV004) immediately forwards exact same amount to Russia. Classic mirror trade.",
    },
    {
        "id": "ADV006",
        "amount": 3500.00,
        "sender_country": "US",
        "receiver_country": "US",
        "transaction_type": "internal",
        "velocity_24h": 1,
        "is_round_number": False,
        "prior_flags": 0,
        "amount_vs_avg_ratio": 0.97,
        "high_risk_country": False,
        "structuring_indicator": False,
        "shell_company_indicator": False,
        "pep_involved": False,
        "notes": "Transfer to registered charity 'Children's Future Fund'. Charity has valid 501c3. Amount is small.",
    },
    {
        "id": "ADV007",
        "amount": 180000.00,
        "sender_country": "AE",
        "receiver_country": "US",
        "transaction_type": "wire",
        "velocity_24h": 1,
        "is_round_number": False,
        "prior_flags": 0,
        "amount_vs_avg_ratio": 1.2,
        "high_risk_country": False,
        "structuring_indicator": False,
        "shell_company_indicator": False,
        "pep_involved": False,
        "notes": "Real estate purchase from UAE. Buyer is an LLC. No individual owner identified. Anonymous LLC red flag.",
    },
    {
        "id": "ADV008",
        "amount": 47500.00,
        "sender_country": "US",
        "receiver_country": "US",
        "transaction_type": "crypto",
        "velocity_24h": 8,
        "is_round_number": False,
        "prior_flags": 3,
        "amount_vs_avg_ratio": 6.2,
        "high_risk_country": False,
        "structuring_indicator": False,
        "shell_company_indicator": False,
        "pep_involved": False,
        "notes": "Crypto transaction routed through Tornado Cash mixer. Output wallet is new with no history.",
    },
    {
        "id": "ADV009",
        "amount": 1200.00,
        "sender_country": "US",
        "receiver_country": "US",
        "transaction_type": "internal",
        "velocity_24h": 1,
        "is_round_number": False,
        "prior_flags": 0,
        "amount_vs_avg_ratio": 1.0,
        "high_risk_country": False,
        "structuring_indicator": False,
        "shell_company_indicator": False,
        "pep_involved": False,
        "notes": "Medical bill payment to hospital. Completely routine.",
    },
    {
        "id": "ADV010",
        "amount": 75000.00,
        "sender_country": "US",
        "receiver_country": "US",
        "transaction_type": "wire",
        "velocity_24h": 1,
        "is_round_number": False,
        "prior_flags": 0,
        "amount_vs_avg_ratio": 1.6,
        "high_risk_country": False,
        "structuring_indicator": False,
        "shell_company_indicator": False,
        "pep_involved": False,
        "notes": "Payment to 'Global Humanitarian Aid' — registered charity but recently flagged by FATF for front abuse. Amount is unusually large for this donor's history.",
    },
    {
        "id": "ADV011",
        "amount": 5600.00,
        "sender_country": "US",
        "receiver_country": "US",
        "transaction_type": "internal",
        "velocity_24h": 1,
        "is_round_number": False,
        "prior_flags": 0,
        "amount_vs_avg_ratio": 1.05,
        "high_risk_country": False,
        "structuring_indicator": False,
        "shell_company_indicator": False,
        "pep_involved": False,
        "notes": "Monthly salary credit from verified employer (Fortune 500). Completely normal.",
    },
    {
        "id": "ADV012",
        "amount": 9100.00,
        "sender_country": "US",
        "receiver_country": "US",
        "transaction_type": "cash",
        "velocity_24h": 1,
        "is_round_number": False,
        "prior_flags": 0,
        "amount_vs_avg_ratio": 1.0,
        "high_risk_country": False,
        "structuring_indicator": False,
        "shell_company_indicator": False,
        "pep_involved": False,
        "notes": "Same account as ADV001 and ADV002. Third deposit in 10 days. Aggregate = $18,850. Delayed structuring.",
    },
    {
        "id": "ADV013",
        "amount": 300000.00,
        "sender_country": "RU",
        "receiver_country": "US",
        "transaction_type": "wire",
        "velocity_24h": 1,
        "is_round_number": True,
        "prior_flags": 0,
        "amount_vs_avg_ratio": 0.0,
        "high_risk_country": True,
        "structuring_indicator": False,
        "shell_company_indicator": True,
        "pep_involved": True,
        "notes": "New entity. Wire from Russian shell to purchase luxury condo. Beneficial owner is Kremlin-linked oligarch.",
    },
    {
        "id": "ADV014",
        "amount": 4200.00,
        "sender_country": "US",
        "receiver_country": "US",
        "transaction_type": "internal",
        "velocity_24h": 2,
        "is_round_number": False,
        "prior_flags": 0,
        "amount_vs_avg_ratio": 1.1,
        "high_risk_country": False,
        "structuring_indicator": False,
        "shell_company_indicator": False,
        "pep_involved": False,
        "notes": "College tuition payment to accredited university. Student loan documentation on file.",
    },
    {
        "id": "ADV015",
        "amount": 19500.00,
        "sender_country": "US",
        "receiver_country": "US",
        "transaction_type": "wire",
        "velocity_24h": 1,
        "is_round_number": False,
        "prior_flags": 1,
        "amount_vs_avg_ratio": 3.5,
        "high_risk_country": False,
        "structuring_indicator": False,
        "shell_company_indicator": False,
        "pep_involved": False,
        "notes": "Wire to car dealership. Customer says it's a car purchase but no dealer invoice provided. Amount is odd for standard car sale.",
    },
]

TRIAGE_ADVERSARIAL_GROUND_TRUTH = [
    {"transaction_id": "ADV001", "true_label": "suspicious", "risk_level": "medium",
     "explanation": "Delayed smurfing — part of a 3-deposit pattern. Individually clean, collectively over $18k."},
    {"transaction_id": "ADV002", "true_label": "suspicious", "risk_level": "medium",
     "explanation": "Second deposit in smurfing pattern. Cross-transaction analysis required."},
    {"transaction_id": "ADV003", "true_label": "suspicious", "risk_level": "high",
     "explanation": "Trade-based money laundering — over-invoiced vague consulting services from China."},
    {"transaction_id": "ADV004", "true_label": "suspicious", "risk_level": "high",
     "explanation": "Mirror trade setup — funds sent to unregistered Swiss 'investment manager'."},
    {"transaction_id": "ADV005", "true_label": "suspicious", "risk_level": "high",
     "explanation": "Mirror trade completion — same amount immediately forwarded to Russia shell."},
    {"transaction_id": "ADV006", "true_label": "legitimate", "risk_level": "low",
     "explanation": "Small donation to legitimate charity. No red flags at this amount."},
    {"transaction_id": "ADV007", "true_label": "suspicious", "risk_level": "high",
     "explanation": "Anonymous LLC real estate — beneficial ownership concealed, high-value property."},
    {"transaction_id": "ADV008", "true_label": "suspicious", "risk_level": "high",
     "explanation": "Tornado Cash mixer output — deliberate obfuscation of crypto trail."},
    {"transaction_id": "ADV009", "true_label": "legitimate", "risk_level": "low",
     "explanation": "Routine medical bill payment."},
    {"transaction_id": "ADV010", "true_label": "suspicious", "risk_level": "high",
     "explanation": "Charity front abuse — FATF-flagged organization, abnormally large for donor profile."},
    {"transaction_id": "ADV011", "true_label": "legitimate", "risk_level": "low",
     "explanation": "Verified salary from Fortune 500 employer."},
    {"transaction_id": "ADV012", "true_label": "suspicious", "risk_level": "high",
     "explanation": "Third smurfing deposit — aggregate with ADV001+ADV002 = $18,850 over 10 days."},
    {"transaction_id": "ADV013", "true_label": "suspicious", "risk_level": "high",
     "explanation": "Kremlin-linked oligarch using Russian shell for US luxury real estate purchase."},
    {"transaction_id": "ADV014", "true_label": "legitimate", "risk_level": "low",
     "explanation": "Documented tuition payment with student loan records."},
    {"transaction_id": "ADV015", "true_label": "suspicious", "risk_level": "medium",
     "explanation": "Suspicious wire to car dealer with no invoice — possible vehicle-based laundering."},
]

TRIAGE_ADVERSARIAL_BUDGET = 4


# ── Task 4: triage_chain (Expert) ────────────────────────────────────────────
# Multi-country layering chain: Colombia → Panama → Cyprus → UAE → US
# Agent must identify the FULL chain to earn maximum score.

TRIAGE_CHAIN_TRANSACTIONS = [
    {
        "id": "CHN001",
        "amount": 95000.00,
        "sender_country": "CO",
        "receiver_country": "PA",
        "transaction_type": "wire",
        "velocity_24h": 1,
        "is_round_number": False,
        "prior_flags": 2,
        "amount_vs_avg_ratio": 12.5,
        "high_risk_country": True,
        "structuring_indicator": False,
        "shell_company_indicator": True,
        "pep_involved": False,
        "notes": "Large wire from Colombian agricultural export company to Panama holding company. Export volumes don't match the wire amount. Placement stage.",
    },
    {
        "id": "CHN002",
        "amount": 93500.00,
        "sender_country": "PA",
        "receiver_country": "CY",
        "transaction_type": "wire",
        "velocity_24h": 1,
        "is_round_number": False,
        "prior_flags": 0,
        "amount_vs_avg_ratio": 0.0,
        "high_risk_country": False,
        "structuring_indicator": False,
        "shell_company_indicator": True,
        "pep_involved": False,
        "notes": "Panama holding (receiver of CHN001) forwards ~same amount (minus 1.5% fee) to Cyprus shell 2 days later. Layering.",
    },
    {
        "id": "CHN003",
        "amount": 88000.00,
        "sender_country": "CY",
        "receiver_country": "AE",
        "transaction_type": "wire",
        "velocity_24h": 1,
        "is_round_number": False,
        "prior_flags": 0,
        "amount_vs_avg_ratio": 0.0,
        "high_risk_country": False,
        "structuring_indicator": False,
        "shell_company_indicator": True,
        "pep_involved": True,
        "notes": "Cyprus shell (receiver of CHN002) sends to UAE company. UAE beneficial owner is PEP (Latin American official). Further layering.",
    },
    {
        "id": "CHN004",
        "amount": 25000.00,
        "sender_country": "US",
        "receiver_country": "US",
        "transaction_type": "wire",
        "velocity_24h": 1,
        "is_round_number": False,
        "prior_flags": 0,
        "amount_vs_avg_ratio": 1.1,
        "high_risk_country": False,
        "structuring_indicator": False,
        "shell_company_indicator": False,
        "pep_involved": False,
        "notes": "Payment for architectural services. Firm is licensed and invoice matches work scope. Normal transaction.",
    },
    {
        "id": "CHN005",
        "amount": 85000.00,
        "sender_country": "AE",
        "receiver_country": "US",
        "transaction_type": "wire",
        "velocity_24h": 1,
        "is_round_number": False,
        "prior_flags": 0,
        "amount_vs_avg_ratio": 0.0,
        "high_risk_country": False,
        "structuring_indicator": False,
        "shell_company_indicator": False,
        "pep_involved": False,
        "notes": "UAE company (receiver of CHN003) purchases US luxury real estate. Appears legitimate on surface — integration stage of laundering chain.",
    },
    {
        "id": "CHN006",
        "amount": 7800.00,
        "sender_country": "US",
        "receiver_country": "US",
        "transaction_type": "internal",
        "velocity_24h": 1,
        "is_round_number": False,
        "prior_flags": 0,
        "amount_vs_avg_ratio": 1.0,
        "high_risk_country": False,
        "structuring_indicator": False,
        "shell_company_indicator": False,
        "pep_involved": False,
        "notes": "Business payroll. Staff count and payroll matches HR records. Routine.",
    },
    {
        "id": "CHN007",
        "amount": 310000.00,
        "sender_country": "CO",
        "receiver_country": "PA",
        "transaction_type": "wire",
        "velocity_24h": 1,
        "is_round_number": False,
        "prior_flags": 2,
        "amount_vs_avg_ratio": 40.0,
        "high_risk_country": True,
        "structuring_indicator": False,
        "shell_company_indicator": True,
        "pep_involved": False,
        "notes": "Second wire from same Colombian company as CHN001, one week later. Significantly larger. Same Panama receiver.",
    },
    {
        "id": "CHN008",
        "amount": 4500.00,
        "sender_country": "US",
        "receiver_country": "US",
        "transaction_type": "cash",
        "velocity_24h": 1,
        "is_round_number": False,
        "prior_flags": 0,
        "amount_vs_avg_ratio": 0.95,
        "high_risk_country": False,
        "structuring_indicator": False,
        "shell_company_indicator": False,
        "pep_involved": False,
        "notes": "Cash deposit from restaurant owner. Amount consistent with weekend cash sales. POS records provided.",
    },
    {
        "id": "CHN009",
        "amount": 305000.00,
        "sender_country": "PA",
        "receiver_country": "CY",
        "transaction_type": "wire",
        "velocity_24h": 1,
        "is_round_number": False,
        "prior_flags": 0,
        "amount_vs_avg_ratio": 0.0,
        "high_risk_country": False,
        "structuring_indicator": False,
        "shell_company_indicator": True,
        "pep_involved": False,
        "notes": "Panama entity (same as CHN002) forwards CHN007 funds to Cyprus, again minus a small fee. Second wave layering.",
    },
    {
        "id": "CHN010",
        "amount": 12000.00,
        "sender_country": "US",
        "receiver_country": "GB",
        "transaction_type": "wire",
        "velocity_24h": 1,
        "is_round_number": False,
        "prior_flags": 0,
        "amount_vs_avg_ratio": 1.3,
        "high_risk_country": False,
        "structuring_indicator": False,
        "shell_company_indicator": False,
        "pep_involved": False,
        "notes": "Payment to UK software vendor. Vendor is publicly listed company. Contract on file. Clean.",
    },
]

TRIAGE_CHAIN_GROUND_TRUTH = [
    {"transaction_id": "CHN001", "true_label": "suspicious", "risk_level": "high",
     "explanation": "Placement — Colombian funds enter Panama shell. Export mismatch is red flag."},
    {"transaction_id": "CHN002", "true_label": "suspicious", "risk_level": "high",
     "explanation": "First layering hop — Panama to Cyprus, same amount minus fee. Follows CHN001."},
    {"transaction_id": "CHN003", "true_label": "suspicious", "risk_level": "high",
     "explanation": "Second layering hop — Cyprus to UAE PEP. Full chain now spans 3 countries."},
    {"transaction_id": "CHN004", "true_label": "legitimate", "risk_level": "low",
     "explanation": "Legitimate architectural services payment with proper documentation."},
    {"transaction_id": "CHN005", "true_label": "suspicious", "risk_level": "high",
     "explanation": "Integration — UAE entity (end of chain) buys US real estate. Looks clean without chain context."},
    {"transaction_id": "CHN006", "true_label": "legitimate", "risk_level": "low",
     "explanation": "Normal payroll verified against HR records."},
    {"transaction_id": "CHN007", "true_label": "suspicious", "risk_level": "high",
     "explanation": "Second wave from same Colombian source — larger amount, same laundering route."},
    {"transaction_id": "CHN008", "true_label": "legitimate", "risk_level": "low",
     "explanation": "Legitimate restaurant cash deposit with POS records."},
    {"transaction_id": "CHN009", "true_label": "suspicious", "risk_level": "high",
     "explanation": "Second wave layering — Panama forwards CHN007 funds to Cyprus, same pattern as CHN002."},
    {"transaction_id": "CHN010", "true_label": "legitimate", "risk_level": "low",
     "explanation": "Documented payment to publicly listed UK vendor."},
]

TRIAGE_CHAIN_BUDGET = 4



TASKS: dict[str, dict[str, Any]] = {
    "triage_basic": {
        "transactions": TRIAGE_BASIC_TRANSACTIONS,
        "ground_truth": TRIAGE_BASIC_GROUND_TRUTH,
        "investigation_budget": TRIAGE_BASIC_BUDGET,
        "difficulty": "easy",
        "description": "5 transactions with clear, single-signal AML indicators.",
        "expected_baseline_score": 0.85,
    },
    "triage_network": {
        "transactions": TRIAGE_NETWORK_TRANSACTIONS,
        "ground_truth": TRIAGE_NETWORK_GROUND_TRUTH,
        "investigation_budget": TRIAGE_NETWORK_BUDGET,
        "difficulty": "medium",
        "description": "10 transactions forming a structuring → layering → integration network.",
        "expected_baseline_score": 0.65,
    },
    "triage_adversarial": {
        "transactions": TRIAGE_ADVERSARIAL_TRANSACTIONS,
        "ground_truth": TRIAGE_ADVERSARIAL_GROUND_TRUTH,
        "investigation_budget": TRIAGE_ADVERSARIAL_BUDGET,
        "difficulty": "hard",
        "description": "15 adversarially-crafted transactions with smurfing, mirror trades, charity fronts, and crypto mixers.",
        "expected_baseline_score": 0.45,
    },
    "triage_chain": {
        "transactions": TRIAGE_CHAIN_TRANSACTIONS,
        "ground_truth": TRIAGE_CHAIN_GROUND_TRUTH,
        "investigation_budget": TRIAGE_CHAIN_BUDGET,
        "difficulty": "expert",
        "description": "10 transactions spanning a 4-country laundering chain (CO→PA→CY→AE→US). Agent must identify the full chain for maximum score.",
        "expected_baseline_score": 0.35,
    },
}