"""
Synthetic transaction datasets for AML tasks.
ground_truth: "suspicious" | "legitimate"
"""

TASKS = {
    "triage_basic": {
        "investigation_budget": 2,
        "transactions": [
            {
                "id": "TXN001",
                "amount": 9500.0,
                "sender_country": "US",
                "receiver_country": "US",
                "transaction_type": "cash",
                "velocity_24h": 3,
                "is_round_number": False,
                "prior_flags": 2,
                "amount_vs_avg_ratio": 0.95,
                "high_risk_country": False,
                "structuring_indicator": True,
                "shell_company_indicator": False,
                "pep_involved": False,
                "notes": "Third cash deposit just below $10k threshold this week"
            },
            {
                "id": "TXN002",
                "amount": 250000.0,
                "sender_country": "KP",
                "receiver_country": "US",
                "transaction_type": "wire",
                "velocity_24h": 1,
                "is_round_number": True,
                "prior_flags": 5,
                "amount_vs_avg_ratio": 8.3,
                "high_risk_country": True,
                "structuring_indicator": False,
                "shell_company_indicator": True,
                "pep_involved": True,
                "notes": "Wire from DPRK-linked entity, receiver is new LLC registered 1 week ago"
            },
            {
                "id": "TXN003",
                "amount": 2800.0,
                "sender_country": "US",
                "receiver_country": "US",
                "transaction_type": "internal",
                "velocity_24h": 1,
                "is_round_number": False,
                "prior_flags": 0,
                "amount_vs_avg_ratio": 1.1,
                "high_risk_country": False,
                "structuring_indicator": False,
                "shell_company_indicator": False,
                "pep_involved": False,
                "notes": "Regular bi-weekly payroll transfer, 3-year history"
            },
            {
                "id": "TXN004",
                "amount": 15000.0,
                "sender_country": "DE",
                "receiver_country": "US",
                "transaction_type": "wire",
                "velocity_24h": 1,
                "is_round_number": True,
                "prior_flags": 0,
                "amount_vs_avg_ratio": 1.2,
                "high_risk_country": False,
                "structuring_indicator": False,
                "shell_company_indicator": False,
                "pep_involved": False,
                "notes": "Documented payment from German auto parts supplier, invoice on file"
            },
            {
                "id": "TXN005",
                "amount": 500.0,
                "sender_country": "US",
                "receiver_country": "AE",
                "transaction_type": "crypto",
                "velocity_24h": 12,
                "is_round_number": True,
                "prior_flags": 4,
                "amount_vs_avg_ratio": 0.1,
                "high_risk_country": True,
                "structuring_indicator": True,
                "shell_company_indicator": True,
                "pep_involved": False,
                "notes": "12 crypto transfers today to UAE mixer-linked wallet, same sender as TXN001"
            },
        ],
        "ground_truth": {
            "TXN001": "suspicious",
            "TXN002": "suspicious",
            "TXN003": "legitimate",
            "TXN004": "legitimate",
            "TXN005": "suspicious",
        }
    },

    "triage_network": {
        "investigation_budget": 3,
        "transactions": [
            {
                "id": "TXN101",
                "amount": 8500.0,
                "sender_country": "US",
                "receiver_country": "MX",
                "transaction_type": "wire",
                "velocity_24h": 4,
                "is_round_number": False,
                "prior_flags": 1,
                "amount_vs_avg_ratio": 1.8,
                "high_risk_country": False,
                "structuring_indicator": True,
                "shell_company_indicator": False,
                "pep_involved": False,
                "notes": "Part of 4 transfers today to same MX beneficiary — smurfing pattern"
            },
            {
                "id": "TXN102",
                "amount": 9200.0,
                "sender_country": "US",
                "receiver_country": "MX",
                "transaction_type": "wire",
                "velocity_24h": 4,
                "is_round_number": False,
                "prior_flags": 0,
                "amount_vs_avg_ratio": 1.9,
                "high_risk_country": False,
                "structuring_indicator": True,
                "shell_company_indicator": False,
                "pep_involved": False,
                "notes": "Linked to TXN101 — same beneficiary account in MX"
            },
            {
                "id": "TXN103",
                "amount": 42000.0,
                "sender_country": "MX",
                "receiver_country": "CH",
                "transaction_type": "wire",
                "velocity_24h": 1,
                "is_round_number": False,
                "prior_flags": 0,
                "amount_vs_avg_ratio": 3.5,
                "high_risk_country": False,
                "structuring_indicator": False,
                "shell_company_indicator": True,
                "pep_involved": False,
                "notes": "Layering: MX account received ~$35k today, now wiring $42k to Swiss shell"
            },
            {
                "id": "TXN104",
                "amount": 1200.0,
                "sender_country": "US",
                "receiver_country": "US",
                "transaction_type": "internal",
                "velocity_24h": 1,
                "is_round_number": False,
                "prior_flags": 0,
                "amount_vs_avg_ratio": 1.0,
                "high_risk_country": False,
                "structuring_indicator": False,
                "shell_company_indicator": False,
                "pep_involved": False,
                "notes": "Employee expense reimbursement, receipts submitted"
            },
            {
                "id": "TXN105",
                "amount": 89000.0,
                "sender_country": "CH",
                "receiver_country": "US",
                "transaction_type": "wire",
                "velocity_24h": 1,
                "is_round_number": False,
                "prior_flags": 0,
                "amount_vs_avg_ratio": 0.8,
                "high_risk_country": False,
                "structuring_indicator": False,
                "shell_company_indicator": True,
                "pep_involved": False,
                "notes": "Integration leg: Swiss entity wiring to US real estate LLC — possible property purchase"
            },
            {
                "id": "TXN106",
                "amount": 3500.0,
                "sender_country": "CA",
                "receiver_country": "US",
                "transaction_type": "wire",
                "velocity_24h": 1,
                "is_round_number": False,
                "prior_flags": 0,
                "amount_vs_avg_ratio": 1.1,
                "high_risk_country": False,
                "structuring_indicator": False,
                "shell_company_indicator": False,
                "pep_involved": False,
                "notes": "Freelance payment, SOW on file, Canadian contractor"
            },
            {
                "id": "TXN107",
                "amount": 18000.0,
                "sender_country": "IR",
                "receiver_country": "US",
                "transaction_type": "wire",
                "velocity_24h": 1,
                "is_round_number": True,
                "prior_flags": 3,
                "amount_vs_avg_ratio": 6.0,
                "high_risk_country": True,
                "structuring_indicator": False,
                "shell_company_indicator": False,
                "pep_involved": True,
                "notes": "Sanctioned jurisdiction wire, PEP involvement, no documented business purpose"
            },
            {
                "id": "TXN108",
                "amount": 450.0,
                "sender_country": "US",
                "receiver_country": "IN",
                "transaction_type": "wire",
                "velocity_24h": 1,
                "is_round_number": False,
                "prior_flags": 0,
                "amount_vs_avg_ratio": 0.9,
                "high_risk_country": False,
                "structuring_indicator": False,
                "shell_company_indicator": False,
                "pep_involved": False,
                "notes": "Family remittance to India, consistent with monthly pattern"
            },
            {
                "id": "TXN109",
                "amount": 9700.0,
                "sender_country": "US",
                "receiver_country": "MX",
                "transaction_type": "wire",
                "velocity_24h": 4,
                "is_round_number": False,
                "prior_flags": 1,
                "amount_vs_avg_ratio": 2.0,
                "high_risk_country": False,
                "structuring_indicator": True,
                "shell_company_indicator": False,
                "pep_involved": False,
                "notes": "Third transfer in smurfing pattern with TXN101/TXN102 — same beneficiary"
            },
            {
                "id": "TXN110",
                "amount": 5000.0,
                "sender_country": "US",
                "receiver_country": "US",
                "transaction_type": "internal",
                "velocity_24h": 1,
                "is_round_number": True,
                "prior_flags": 0,
                "amount_vs_avg_ratio": 1.0,
                "high_risk_country": False,
                "structuring_indicator": False,
                "shell_company_indicator": False,
                "pep_involved": False,
                "notes": "Quarterly bonus payment, HR-approved, documented"
            },
        ],
        "ground_truth": {
            "TXN101": "suspicious",
            "TXN102": "suspicious",
            "TXN103": "suspicious",
            "TXN104": "legitimate",
            "TXN105": "suspicious",
            "TXN106": "legitimate",
            "TXN107": "suspicious",
            "TXN108": "legitimate",
            "TXN109": "suspicious",
            "TXN110": "legitimate",
        }
    },

    "triage_adversarial": {
        "investigation_budget": 4,
        "transactions": [
            {
                "id": "TXN201",
                "amount": 12000.0,
                "sender_country": "US",
                "receiver_country": "US",
                "transaction_type": "wire",
                "velocity_24h": 1,
                "is_round_number": True,
                "prior_flags": 0,
                "amount_vs_avg_ratio": 1.3,
                "high_risk_country": False,
                "structuring_indicator": False,
                "shell_company_indicator": False,
                "pep_involved": False,
                "notes": "Payment to 'Global Humanitarian Aid Foundation' — charity front. Receiver has <6 months history, no Form 990 filing."
            },
            {
                "id": "TXN202",
                "amount": 175000.0,
                "sender_country": "US",
                "receiver_country": "AE",
                "transaction_type": "wire",
                "velocity_24h": 1,
                "is_round_number": False,
                "prior_flags": 0,
                "amount_vs_avg_ratio": 2.1,
                "high_risk_country": True,
                "structuring_indicator": False,
                "shell_company_indicator": False,
                "pep_involved": False,
                "notes": "Trade invoice for 500 units 'industrial equipment' at $350/unit. Market price ~$80/unit. Over-invoiced TBML indicator."
            },
            {
                "id": "TXN203",
                "amount": 8900.0,
                "sender_country": "US",
                "receiver_country": "US",
                "transaction_type": "cash",
                "velocity_24h": 2,
                "is_round_number": False,
                "prior_flags": 1,
                "amount_vs_avg_ratio": 1.7,
                "high_risk_country": False,
                "structuring_indicator": True,
                "shell_company_indicator": False,
                "pep_involved": False,
                "notes": "Restaurant business, cash-intensive. Below CTR threshold but consistent with legitimate daily revenue."
            },
            {
                "id": "TXN204",
                "amount": 22000.0,
                "sender_country": "RU",
                "receiver_country": "US",
                "transaction_type": "wire",
                "velocity_24h": 1,
                "is_round_number": True,
                "prior_flags": 0,
                "amount_vs_avg_ratio": 1.0,
                "high_risk_country": True,
                "structuring_indicator": False,
                "shell_company_indicator": False,
                "pep_involved": False,
                "notes": "Mirror trade: simultaneous $22k wire RU→US and matching $22k wire US→RU from different accounts same bank."
            },
            {
                "id": "TXN205",
                "amount": 650.0,
                "sender_country": "US",
                "receiver_country": "NG",
                "transaction_type": "crypto",
                "velocity_24h": 1,
                "is_round_number": False,
                "prior_flags": 0,
                "amount_vs_avg_ratio": 0.8,
                "high_risk_country": False,
                "structuring_indicator": False,
                "shell_company_indicator": False,
                "pep_involved": False,
                "notes": "Crypto remittance platform transfer. Customer verified KYC. Family support documented."
            },
            {
                "id": "TXN206",
                "amount": 95000.0,
                "sender_country": "US",
                "receiver_country": "US",
                "transaction_type": "wire",
                "velocity_24h": 1,
                "is_round_number": False,
                "prior_flags": 0,
                "amount_vs_avg_ratio": 1.0,
                "high_risk_country": False,
                "structuring_indicator": False,
                "shell_company_indicator": False,
                "pep_involved": False,
                "notes": "Real estate purchase earnest money. Title company verified. Clean source of funds documentation."
            },
            {
                "id": "TXN207",
                "amount": 45000.0,
                "sender_country": "BZ",
                "receiver_country": "US",
                "transaction_type": "wire",
                "velocity_24h": 1,
                "is_round_number": False,
                "prior_flags": 2,
                "amount_vs_avg_ratio": 4.5,
                "high_risk_country": True,
                "structuring_indicator": False,
                "shell_company_indicator": True,
                "pep_involved": False,
                "notes": "Crypto mixer output consolidated into Belize LLC then wired to US account. Blockchain analysis shows Hydra darknet origin."
            },
            {
                "id": "TXN208",
                "amount": 3200.0,
                "sender_country": "US",
                "receiver_country": "US",
                "transaction_type": "internal",
                "velocity_24h": 1,
                "is_round_number": False,
                "prior_flags": 0,
                "amount_vs_avg_ratio": 1.0,
                "high_risk_country": False,
                "structuring_indicator": False,
                "shell_company_indicator": False,
                "pep_involved": False,
                "notes": "University tuition auto-payment, 4-year pattern, student loan disbursement origin."
            },
            {
                "id": "TXN209",
                "amount": 28000.0,
                "sender_country": "US",
                "receiver_country": "US",
                "transaction_type": "wire",
                "velocity_24h": 2,
                "is_round_number": False,
                "prior_flags": 0,
                "amount_vs_avg_ratio": 2.8,
                "high_risk_country": False,
                "structuring_indicator": False,
                "shell_company_indicator": False,
                "pep_involved": False,
                "notes": "Aggregated smurf proceeds now integrated: $28k wire to art dealer for 'investment artwork'. Auction house unregulated."
            },
            {
                "id": "TXN210",
                "amount": 7500.0,
                "sender_country": "US",
                "receiver_country": "CN",
                "transaction_type": "wire",
                "velocity_24h": 1,
                "is_round_number": False,
                "prior_flags": 0,
                "amount_vs_avg_ratio": 1.1,
                "high_risk_country": False,
                "structuring_indicator": False,
                "shell_company_indicator": False,
                "pep_involved": False,
                "notes": "E-commerce supplier payment. Alibaba verified merchant. 2-year import history, consistent with business pattern."
            },
            {
                "id": "TXN211",
                "amount": 180000.0,
                "sender_country": "PA",
                "receiver_country": "US",
                "transaction_type": "wire",
                "velocity_24h": 1,
                "is_round_number": False,
                "prior_flags": 1,
                "amount_vs_avg_ratio": 5.2,
                "high_risk_country": False,
                "structuring_indicator": False,
                "shell_company_indicator": True,
                "pep_involved": True,
                "notes": "Panama Papers-linked offshore entity. Senior government official PEP. Real estate investment described as 'portfolio diversification'."
            },
            {
                "id": "TXN212",
                "amount": 19500.0,
                "sender_country": "US",
                "receiver_country": "US",
                "transaction_type": "wire",
                "velocity_24h": 1,
                "is_round_number": False,
                "prior_flags": 0,
                "amount_vs_avg_ratio": 1.2,
                "high_risk_country": False,
                "structuring_indicator": False,
                "shell_company_indicator": False,
                "pep_involved": False,
                "notes": "Medical equipment purchase from verified supplier. Hospital procurement order on file."
            },
            {
                "id": "TXN213",
                "amount": 4800.0,
                "sender_country": "US",
                "receiver_country": "US",
                "transaction_type": "cash",
                "velocity_24h": 3,
                "is_round_number": False,
                "prior_flags": 3,
                "amount_vs_avg_ratio": 2.2,
                "high_risk_country": False,
                "structuring_indicator": True,
                "shell_company_indicator": False,
                "pep_involved": False,
                "notes": "Nail salon cash-intensive business. Owner has prior SAR filing. Third sub-$5k deposit today."
            },
            {
                "id": "TXN214",
                "amount": 62000.0,
                "sender_country": "US",
                "receiver_country": "AE",
                "transaction_type": "wire",
                "velocity_24h": 1,
                "is_round_number": False,
                "prior_flags": 0,
                "amount_vs_avg_ratio": 1.3,
                "high_risk_country": True,
                "structuring_indicator": False,
                "shell_company_indicator": False,
                "pep_involved": False,
                "notes": "Corporate payment to verified Dubai distributor. 5-year relationship. Trade documentation complete."
            },
            {
                "id": "TXN215",
                "amount": 330000.0,
                "sender_country": "US",
                "receiver_country": "US",
                "transaction_type": "wire",
                "velocity_24h": 1,
                "is_round_number": False,
                "prior_flags": 0,
                "amount_vs_avg_ratio": 1.1,
                "high_risk_country": False,
                "structuring_indicator": False,
                "shell_company_indicator": False,
                "pep_involved": False,
                "notes": "Anonymous LLC purchasing residential real estate — no beneficial owner disclosed. All-cash. High-value real estate AML red flag."
            },
        ],
        "ground_truth": {
            "TXN201": "suspicious",   # Charity front
            "TXN202": "suspicious",   # TBML over-invoicing
            "TXN203": "legitimate",   # Cash-intensive legit business
            "TXN204": "suspicious",   # Mirror trade
            "TXN205": "legitimate",   # Verified remittance
            "TXN206": "legitimate",   # Clean real estate purchase
            "TXN207": "suspicious",   # Crypto mixer → darknet
            "TXN208": "legitimate",   # University tuition
            "TXN209": "suspicious",   # Smurf integration via art
            "TXN210": "legitimate",   # Verified e-commerce
            "TXN211": "suspicious",   # PEP + Panama offshore
            "TXN212": "legitimate",   # Legitimate medical purchase
            "TXN213": "suspicious",   # Structured + prior SAR
            "TXN214": "legitimate",   # Verified corporate
            "TXN215": "suspicious",   # Anonymous LLC real estate
        }
    }
}